parameters:
#    mss_core.example.class: MSS\CoreBundle\Example

services:
#    mss_core.example:
#        class: %mss_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
